<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, shrink-to-fit=no">

  <!-- Meta Tags Generic-->
  <title>Hypha | Privacy Policy</title>
  <meta name="description" content="Hypha set out in 2019 to build tools for creating new economic systems to start to address humanity’s crises, such as SEEDS a regenerative economic system">
  <meta name="og:image" content="https://hypha.earth/img/og-image.jpg">
  <link rel="icon" type="image/png" href="img/favicon.png" />


  <!--  Non-Essential, But Recommended -->

  <meta property="og:site_name" content="Hypha">

  <!-- fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=Raleway:ital,wght@0,300;0,400;0,600;0,700;0,800;1,300;1,400;1,600;1,700&display=swap" rel="stylesheet">

  <!-- css -->
  <link rel="stylesheet" href="css/loader-style.css">
  <link rel="stylesheet" href="css/general-style.css">
  <link rel="stylesheet" href="css/inside-blu-pages.css">
  <link rel="stylesheet" href="css/responsive.css">
  <link rel="stylesheet" href="css/burger-menu.css">

  <!-- Javascript / jQuery libraries -->
  <script src="js/jquery-3-10-1-min.js" type="text/javascript"></script>
  <script src="js/lax.min.js" type="text/javascript"></script>
  <script src="js/parallax.js" type="text/javascript"></script>


  <!-- jquery functions & animations -->
  <script src="js/general-animations.js" type="text/javascript"></script>
  <script src="js/scroll-top.js" type="text/javascript"></script>


</head>
  <body>

    <!--page loader very basic, waits the load of the header background image and disappears-->
    <div class="obscurer">

        <div class="vertical-centered-box">
          <div class="contentt">
            <div class="loader-circle"></div>
            <div class="loader-line-mask">
              <div class="loader-line"></div>
            </div>
            <img src="img/round-logo.svg" height="70" width="70" />
          </div>
        </div>

    </div>

    <?php
        include 'incl/hypha-menu.html';

     ?>


    <main>
      <div class="about-parall parallax" data-image-src="img/3-steps-back.jpg">
      </div>

      <section class="about-header">
        <div class="foglio">
          <a class="backlink" href="javascript:history.back()">Go back</a>
          <h1>Privacy Policy</h1>
          <p class="hero-text">Hypha DHO ("us", "we", or "our") operates the Hypha.earth and dho.hypha.earth websites & mobile sites (the "Service")</p>
        </div>
      </section>


      <section class="about-body">

        <div id="scroll_top"></div>

        <div class="yellowdots lax" data-lax-translate-y="(vh) 1, (-vh) -200" data-lax-anchor="self">
          <img src="img/yellowdots.svg"/>
        </div>
        <div class="foglio">
          <div class="text-body">
            <p>This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.
              <br><br>
              We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy.
            </p>


                <h2 class="section-title-landing">
                    Definitions
                </h2>

                <p class="legal-small-tit ">Service</p>
                <p>Hypha.earth and dho.hypha.earth websites & mobile sites operated by Hypha DHO.</p>

                <p class="legal-small-tit ">Partner Service</p>
                <p>Partner Service means a service or feature offered by a third-party partner directly to users of the Service.</p>

                <p class="legal-small-tit ">Personal Data</p>
                <p>Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>

                <p class="legal-small-tit ">Usage Data</p>
                <p>Usage Data is data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>

                <p class="legal-small-tit ">Cookies</p>
                <p>Cookies are small pieces of data stored on your device (computer or mobile device).</p>

                <p class="legal-small-tit ">Data Controller</p>
                <p>Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed.</p>
                <p>For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.</p>

                <p class="legal-small-tit ">Data Processors (or Service Providers)</p>
                <p>Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller.</p>
                <p>We may use the services of various Service Providers in order to process your data more effectively.</p>

                <p class="legal-small-tit ">Data Subject (or User)</p>
                <p>Data Subject is any living individual who is using our Service and is the subject of Personal Data</p>


                <div class="legal-line"></div>
                <h2 class="section-title-landing">
                    Information Collection and Use
                </h2>

                <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
                <div class="legal-line"></div>


                <h2 class="section-title-landing">
                    Types of Data Collected
                </h2>

                        <p class="legal-small-tit ">Personal Data</p>
                        <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data").</p>
                        <p>The following information may be collected by the Service:</p>
                        <div class="solid-list">
                           <div class="solid-list-item">
                               <div class="list-bullet">
                                   <i class="sl sl-icon-arrow-right"></i>
                               </div>
                               <div class="list-text">
                                   Cookies and Usage Data
                               </div>
                           </div>
                           <div class="solid-list-item">
                               <div class="list-bullet">
                                   <i class="sl sl-icon-arrow-right"></i>
                               </div>
                               <div class="list-text">
                                   Telos Account Name
                               </div>
                           </div>
                           <div class="solid-list-item">
                               <div class="list-bullet">
                                   <i class="sl sl-icon-arrow-right"></i>
                               </div>
                               <div class="list-text">
                                 Email Address
                               </div>
                           </div>
                       </div>

                       <p>
                         If you sign up for our mailing list or beta test program, you will be asked to provide the following:
                       </p>
                       <div class="solid-list">
                          <div class="solid-list-item">
                              <div class="list-bullet">
                                  <i class="sl sl-icon-arrow-right"></i>
                              </div>
                              <div class="list-text">
                                  Email address
                              </div>
                          </div>
                      </div>

                      <p>
                        If you elect to use a Partner Service, the Partner Service may ask you to provide personally identifiable information including, but not limited to, the following:
                      </p>
                      <div class="solid-list">
                         <div class="solid-list-item">
                             <div class="list-bullet">
                                 <i class="sl sl-icon-arrow-right"></i>
                             </div>
                             <div class="list-text">
                                 Email address
                             </div>
                         </div>
                         <div class="solid-list-item">
                             <div class="list-bullet">
                                 <i class="sl sl-icon-arrow-right"></i>
                             </div>
                             <div class="list-text">
                               First name and last name
                             </div>
                         </div>
                         <div class="solid-list-item">
                             <div class="list-bullet">
                                 <i class="sl sl-icon-arrow-right"></i>
                             </div>
                             <div class="list-text">
                                 Phone number
                             </div>
                         </div>
                         <div class="solid-list-item">
                             <div class="list-bullet">
                                 <i class="sl sl-icon-arrow-right"></i>
                             </div>
                             <div class="list-text">
                                 Address, State, Province, ZIP/Postal code, City
                             </div>
                         </div>
                     </div>

                    <p>
                      If provided, your email address may be used to contact you with newsletters, marketing or promotional materials, and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send or by contacting us.
                    </p>



                    <p class="legal-small-tit ">Usage Data</p>
                    <p>We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device ("Usage Data").</p>
                    <p>This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers, and other diagnostic data.</p>
                    <p>When you access the Service by or through a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.</p>


                    <p class="legal-small-tit ">Location Data</p>
                    <p>We may use and store information about your location if you give us permission to do so (“Location Data”). We use this data to provide features of our Service, and to improve and customize our Service.</p>
                    <p>You can enable or disable location services when you use our Service at any time, through your device settings.</p>

                    <p id="cookie-anchor" class="legal-small-tit ">Tracking Cookies Data</p>
                    <p>We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.</p>
                    <p>Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.</p>
                    <p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent.</p>
                    <p>Examples of Cookies we use:</p>
                    <div class="solid-list">
                       <div class="solid-list-item">
                           <div class="list-bullet">
                               <i class="sl sl-icon-arrow-right"></i>
                           </div>
                           <div class="list-text">
                               Session Cookies. We use Session Cookies to operate our Service.
                           </div>
                       </div>
                       <div class="solid-list-item">
                           <div class="list-bullet">
                               <i class="sl sl-icon-arrow-right"></i>
                           </div>
                           <div class="list-text">
                             Preference Cookies. We use Preference Cookies to remember your preferences and various settings.
                           </div>
                       </div>
                       <div class="solid-list-item">
                           <div class="list-bullet">
                               <i class="sl sl-icon-arrow-right"></i>
                           </div>
                           <div class="list-text">
                               Security Cookies. We use Security Cookies for security purposes.
                           </div>
                       </div>
                     </div>



                    <p class="legal-small-tit ">Use of Data</p>
                    <p>Hypha DHO uses the collected data for various purposes:</p>
                    <div class="solid-list">
                       <div class="solid-list-item">
                           <div class="list-bullet">
                               <i class="sl sl-icon-arrow-right"></i>
                           </div>
                           <div class="list-text">
                               To provide and maintain our Service
                           </div>
                       </div>
                       <div class="solid-list-item">
                           <div class="list-bullet">
                               <i class="sl sl-icon-arrow-right"></i>
                           </div>
                           <div class="list-text">
                             To allow you to participate in interactive features of our Service when you choose to do so
                           </div>
                       </div>
                       <div class="solid-list-item">
                           <div class="list-bullet">
                               <i class="sl sl-icon-arrow-right"></i>
                           </div>
                           <div class="list-text">
                               To gather analysis or valuable information so that we can improve our Service
                           </div>
                       </div>
                       <div class="solid-list-item">
                           <div class="list-bullet">
                               <i class="sl sl-icon-arrow-right"></i>
                           </div>
                           <div class="list-text">
                               To monitor the usage of our Service
                           </div>
                       </div>
                       <div class="solid-list-item">
                           <div class="list-bullet">
                               <i class="sl sl-icon-arrow-right"></i>
                           </div>
                           <div class="list-text">
                               To detect, prevent and address technical issues
                           </div>
                       </div>
                       <div class="solid-list-item">
                           <div class="list-bullet">
                               <i class="sl sl-icon-arrow-right"></i>
                           </div>
                           <div class="list-text">
                               To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information
                           </div>
                       </div>
                     </div>




                    <p class="legal-small-tit ">Legal Basis for Processing Personal Data Under General Data Protection Regulation (GDPR)</p>
                    <p>If you are from the European Economic Area (EEA), Hypha DHO’s legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.</p>
                    <p>Hypha DHO may process your Personal Data because:</p>
                    <div class="solid-list">
                       <div class="solid-list-item">
                           <div class="list-bullet">
                               <i class="sl sl-icon-arrow-right"></i>
                           </div>
                           <div class="list-text">
                               We need to perform a contract with you
                           </div>
                       </div>
                       <div class="solid-list-item">
                           <div class="list-bullet">
                               <i class="sl sl-icon-arrow-right"></i>
                           </div>
                           <div class="list-text">
                             You have given us permission to do so
                           </div>
                       </div>
                       <div class="solid-list-item">
                           <div class="list-bullet">
                               <i class="sl sl-icon-arrow-right"></i>
                           </div>
                           <div class="list-text">
                               The processing is in our legitimate interests and is not overridden by your rights
                           </div>
                       </div>
                       <div class="solid-list-item">
                           <div class="list-bullet">
                               <i class="sl sl-icon-arrow-right"></i>
                           </div>
                           <div class="list-text">
                               It is required to comply with the law
                           </div>
                       </div>
                     </div>


                    <p class="legal-small-tit ">Retention of Data</p>
                    <p>Hypha DHO will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
                    <p>Hypha DHO will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>

                    <p class="legal-small-tit ">Transfer of Data</p>
                    <p>Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</p>
                    <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
                    <p>Hypha DHO will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>

                    <div class="legal-line"></div>

                    <h2 class="section-title-landing">
                        Disclosure of Data
                    </h2>

                    <p class="legal-small-tit ">Legal Requirement</p>
                    <p>Hypha DHO may disclose your Personal Data in the good faith belief that such action is necessary to:</p>

                    <div class="solid-list">
                       <div class="solid-list-item">
                           <div class="list-bullet">
                               <i class="sl sl-icon-arrow-right"></i>
                           </div>
                           <div class="list-text">
                               To comply with a legal obligation
                           </div>
                       </div>
                       <div class="solid-list-item">
                           <div class="list-bullet">
                               <i class="sl sl-icon-arrow-right"></i>
                           </div>
                           <div class="list-text">
                             To protect and defend the rights or property of Hypha DHO
                           </div>
                       </div>
                       <div class="solid-list-item">
                           <div class="list-bullet">
                               <i class="sl sl-icon-arrow-right"></i>
                           </div>
                           <div class="list-text">
                               To prevent or investigate possible wrongdoing in connection with the Service
                           </div>
                       </div>
                       <div class="solid-list-item">
                           <div class="list-bullet">
                               <i class="sl sl-icon-arrow-right"></i>
                           </div>
                           <div class="list-text">
                               To protect the personal safety of users of the Service or the public
                           </div>
                       </div>
                       <div class="solid-list-item">
                           <div class="list-bullet">
                               <i class="sl sl-icon-arrow-right"></i>
                           </div>
                           <div class="list-text">
                               To protect against legal liability
                           </div>
                       </div>
                     </div>


                     <p class="legal-small-tit ">Security of Data</p>
                     <p>The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>

                     <p class="legal-small-tit ">Your Data Protection Rights Under General Data Protection Regulation (GDPR)</p>
                     <p>If you are a resident of the European Economic Area (EEA), you have certain data protection rights. Hypha DHO aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.</p>
                     <p>If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please contact us at <a href="mailto:hello@hypha.earth">hello@hypha.earth</a></p>
                     <p>In certain circumstances, you have the following data protection rights:</p>
                     <p>The right to access, update or to delete the information we have on you. Whenever made possible, you can access, update or request deletion of your Personal Data directly within your account settings section. If you are unable to perform these actions yourself, please contact us to assist you.</p>
                     <p>The right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete.</p>
                     <p>The right to object. You have the right to object to our processing of your Personal Data.</p>
                     <p>The right of restriction. You have the right to request that we restrict the processing of your personal information.</p>
                     <p>The right to data portability. You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.</p>
                     <p>The right to withdraw consent. You also have the right to withdraw your consent at any time where Hypha DHO relied on your consent to process your personal information.</p>
                     <p>Please note that we may ask you to verify your identity before responding to such requests.</p>
                     <p>You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).</p>

                     <p class="legal-small-tit ">Service Providers</p>
                     <p>We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.
                      These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
                      </p>

                      <div class="legal-line"></div>

                      <h2 class="section-title-landing">
                          Analytics
                      </h2>

                      <p class="legal-small-tit ">Google Analytics</p>
                      <p>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.</p>
                      <p>For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: <a href="http://www.google.com/intl/en/policies/privacy/">http://www.google.com/intl/en/policies/privacy</a></p>

                        <div class="legal-line"></div>

                        <h2 class="section-title-landing">
                            Links To Other Sites
                        </h2>

                        <p>Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
                        <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

                      <div class="legal-line"></div>

                      <h2 class="section-title-landing">
                          Children's Privacy
                      </h2>

                      <p>Our Service does not address anyone under the age of 18 ("Children").</p>
                      <p>We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Children has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>

                    <div class="legal-line"></div>
                    <h2 class="section-title-landing">
                        Changes To This Privacy Policy
                    </h2>

                    <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page, and will update the "effective date" at the top of this Privacy Policy.</p>
                    <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

                    <div class="legal-line"></div>
                    <h2 class="section-title-landing">
                      Contact Us
                    </h2>

                    <p>If you have any questions about this Privacy Policy, please contact us by email: </p>
                    <p><a href="mailto:hello@hypha.earth">hello@hypha.earth</a></p>



            <div class="space-text"></div>

          </div>
        <div class="foglio">

      </section>
    </main>

    <?php
        include 'incl/hypha-footer.html';

     ?>





  </body>
</html>
