<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, shrink-to-fit=no">

  <!-- Meta Tags Generic-->
  <title>Hypha | Work with us</title>
  <meta name="description" content="Work in a dynamic global organisation where mutual respect, support, joy, meaning, and professionalism abound">
  <meta name="og:image" content="https://hypha.earth/img/og-image.jpg">
  <link rel="icon" type="image/png" href="img/favicon.png" />


  <!--  Non-Essential, But Recommended -->

  <meta property="og:site_name" content="Hypha">

  <!-- fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=Raleway:ital,wght@0,300;0,400;0,600;0,700;0,800;1,300;1,400;1,600;1,700&display=swap" rel="stylesheet">

  <!-- css -->
  <link rel="stylesheet" href="css/loader-style.css">
  <link rel="stylesheet" href="css/general-style.css">
  <link rel="stylesheet" href="css/inside-blu-pages.css">
  <link rel="stylesheet" href="css/responsive.css">
  <link rel="stylesheet" href="css/burger-menu.css">

  <!-- Javascript / jQuery libraries -->
  <script src="js/jquery-3-10-1-min.js" type="text/javascript"></script>
  <script src="js/lax.min.js" type="text/javascript"></script>
  <script src="js/parallax.js" type="text/javascript"></script>


  <!-- jquery functions & animations -->
  <script src="js/general-animations.js" type="text/javascript"></script>


</head>
  <body>

    <!--page loader very basic, waits the load of the header background image and disappears-->
    <div class="obscurer">

        <div class="vertical-centered-box">
          <div class="contentt">
            <div class="loader-circle"></div>
            <div class="loader-line-mask">
              <div class="loader-line"></div>
            </div>
            <img src="img/round-logo.svg" height="70" width="70" />
          </div>
        </div>

    </div>

    <?php
        include 'incl/hypha-menu.html';

     ?>


    <main>
      <div class="about-parall parallax" data-image-src="img/3-steps-back.jpg">
      </div>

      <section class="about-header">
        <div class="foglio">
          <h1>Work <br>with us</h1>
          <p class="hero-text">Work in a dynamic global organisation where mutual respect, support, joy, meaning, and professionalism abound</p>
        </div>
      </section>


      <section class="about-body">
        <div class="yellowdots lax" data-lax-translate-y="(vh) 1, (-vh) -200" data-lax-anchor="self">
          <img src="img/yellowdots.svg"/>
        </div>
        <div class="foglio">
          <div class="text-body">
            <p class="text-body-h4">Why work with us?</p>
            <ul>
              <li><strong>Innovation:</strong> Work on projects that are at the forefront of new technological and organisational ecosystems that will change the way organisations will work in the future.</li>
              <li><strong>Compensation:</strong> Hypha provides competitive compensation options.</li>
              <li><strong>Work schedule:</strong> No fixed hours - we believe real creativity doesn’t happen between 9-5 for all people. Compensation is based on contributions - not hours.</li>
              <li><strong>Remote working:</strong> Work from anywhere in the world.</li>
              <li><strong>Culture:</strong> Work in a dynamic global organisation where mutual respect, support, joy, meaning, and professionalism abound.</li>
            </ul>

            <div class="space-text"></div>
            <p class="text-body-h4">how to apply?</p>
            <ul>
              <li>Go to <a href="https://dho.hypha.earth" target="_blank">dho.hypha.earth</a>  and login, then click the + tab on quests, contributions or assignments:</li>
              <li>A <strong>Quest</strong> is where you agree to a specific one-time task generated by the DAO members that has a reward associated with it. Evaluation of success and rewards are distributed after various milestones are (or the whole quest is) done.</li>
              <li><strong>Open Contributions</strong> afford the most freedom as you’re able to freely create value and then after-the-fact make a proposal to see if the members would like to compensate you for that value. These proposals have a lower chance of success to Quests as members haven’t agreed to whether or not they wanted that contribution. However, this ability allows a DAO to receive valuable contributions that may have not been previously thought of before.</li>
              <li><strong>Assignments</strong> are a recurring contribution that last for a period of time (maximum 3 lunar cycles). Members who are regularly and consistently adding value may apply for an assignment.</li>
            </ul>
            <div class="space-text"></div>
            <p class="text-body-h4">The best first step to joining Hypha and to get more information is to join our community chat and say hello: <a href="https://discord.gg/Gx3rmYfjaV" target="_blank">Hypha Discord</a> </p>
            <div class="space-text"></div>
          </div>



        <div class="foglio">

      </section>
    </main>

    <?php
        include 'incl/hypha-footer.html';

     ?>

     <?php
         include 'incl/video2.html';
      ?>


  </body>
</html>
